# Generated by Django 3.0.7 on 2020-12-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_stray'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stray',
            options={'ordering': ['arrival_date']},
        ),
    ]
