# Generated by Django 3.0.7 on 2020-12-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20201215_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='stray',
            name='image',
            field=models.ImageField(default='stray.jpg', upload_to='stray_pics'),
        ),
    ]
